version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9  # Install Python 3.9

  pre_build:
    commands:
      - echo "==== CHECK IF PYTHON AND AWSCLI ARE INSTALLED ===="
      - python3 --version
      - aws --version

  build:
    commands:
      - echo "==== RUNNING YOUR PYTHON SCRIPT ===="
      - python3 my_app.py  # Run your custom Python script

  post_build:
    commands:
      - echo "==== BUILD COMPLETE ===="
      - echo "Build finished at `date`"

artifacts:
  files:
    - ec2-apache-static-site.yaml  # Include this so the deploy stage can use it


