---
- name: Install Apache webserver on Ubuntu clients
  hosts: ubuntu-clients
  become: yes
  vars_files:
    - variables.yaml

  tasks:
    - name: Update all packages
      apt:
        update_cache: yes

    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Ensure Apache is running
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Copy custom index.html
      copy:
        src: index.html
        dest: /var/www/html/index.html
        mode: '0644'

- name: Install Git on Ubuntu clients
  hosts: ubuntu-clients
  become: yes

  tasks:
    - name: Install Git
      apt:
        name: git
        state: present

- name: Debug my name on all hosts
  hosts: all
  vars_files:
    - variables.yaml

  tasks:
    - name: Display name using debug
      debug:
        msg: "My name is {{ my_name }}"